import AniNumber from './aniNumber';
import Button from './button';
import ButtonGroup from './buttonGroup';
import Calendar from './calendar';
import Circle from './circle';
import Dashboard from './dashboard';
import Floating from './floating';
import GridBar from './gridBar';
import Icons from './iocns';
import Ring from './ring';
import Progress from './progress';
export default [AniNumber, Button, ButtonGroup, Calendar, Circle, Dashboard,Floating, GridBar, Icons, Progress, Ring];
